oro_organization_bundle:
    resource:     "@OroOrganizationBundle/Controller"
    type:         attribute
    prefix:       /organization


#
# OLD REST API ROUTES
#

oro_api_get_businessunits:
    path: '/api/rest/{version}/businessunits.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\OrganizationBundle\Controller\Api\Rest\BusinessUnitController::cgetAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1

oro_api_post_businessunit:
    path: '/api/rest/{version}/businessunits.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\OrganizationBundle\Controller\Api\Rest\BusinessUnitController::postAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1

oro_api_put_businessunit:
    path: '/api/rest/{version}/businessunits/{id}.{_format}'
    methods: [PUT]
    defaults:
        _controller: 'Oro\Bundle\OrganizationBundle\Controller\Api\Rest\BusinessUnitController::putAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_api_get_businessunit:
    path: '/api/rest/{version}/businessunits/{id}.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\OrganizationBundle\Controller\Api\Rest\BusinessUnitController::getAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_api_delete_businessunit:
    path: '/api/rest/{version}/businessunits/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\OrganizationBundle\Controller\Api\Rest\BusinessUnitController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_api_options_businessunits:
    path: '/api/rest/{version}/businessunits.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\OrganizationBundle\Controller\Api\Rest\BusinessUnitController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1
