oro_config:
    resource:     "@OroConfigBundle/Controller"
    type:         attribute
    prefix:       /config


#
# OLD REST API ROUTES
#

oro_api_get_configurations:
    path: '/api/rest/{version}/configuration.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\ConfigBundle\Controller\Api\Rest\ConfigurationController::cgetAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1

oro_api_get_configuration:
    path: '/api/rest/{version}/configuration/{path}.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\ConfigBundle\Controller\Api\Rest\ConfigurationController::getAction'
        _format: json
        version: latest
    requirements:
        path: '[\w\-]+[\w\-\/]*'
        _format: json
        version: latest|v1
