oro_comment_bundle:
    resource:     "@OroCommentBundle/Controller"
    type:         attribute
    prefix:       /

#
# OLD REST API ROUTES
#

oro_api_comment_get_items:
    path: '/api/rest/{version}/relation/{relationClass}/{relationId}/comment.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::cgetAction'
        _format: json
        version: latest
    requirements:
        relationId: \d+
        _format: json
        version: latest|v1

oro_api_comment_create_item:
    path: '/api/rest/{version}/relation/{relationClass}/{relationId}/comment.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::postAction'
        _format: json
        version: latest
    requirements:
        relationId: \d+
        _format: json
        version: latest|v1

oro_api_comment_get_item:
    path: '/api/rest/{version}/comment/{id}.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::getAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_api_comment_update_item:
    path: '/api/rest/{version}/comment/{id}.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::putAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_api_comment_remove_attachment_item:
    path: '/api/rest/{version}/comment/{id}/removeAttachment.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::removeAttachmentAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_api_comment_delete_item:
    path: '/api/rest/{version}/comment/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1
