oro_translation_jstranslation:
    path: '/media/js/translation/{_locale}.json'
    defaults:
        _controller: 'Oro\Bundle\TranslationBundle\Controller\JsTranslationController::indexAction'
    options:
        expose: true

oro_translation_service:
    resource:     "@OroTranslationBundle/Controller"
    type:         attribute
    prefix:       /translation

oro_translation_language:
    resource:     "@OroTranslationBundle/Controller/LanguageController.php"
    type:         attribute
    prefix:       /language


#
# OLD REST API ROUTES
#

oro_api_get_translations:
    path: '/api/rest/{version}/translations.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\TranslationBundle\Controller\Api\Rest\TranslationController::cgetAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1

oro_api_patch_translation:
    path: '/api/rest/{version}/translations/{locale}/{domain}/{key}/patch.{_format}'
    methods: [PATCH]
    defaults:
        _controller: 'Oro\Bundle\TranslationBundle\Controller\Api\Rest\TranslationController::patchAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1
