oro_datagrid_bundle:
    resource: "@OroDataGridBundle/Controller"
    type:     attribute
    prefix:   /datagrid


#
# OLD REST API ROUTES
#

oro_datagrid_api_rest_gridview_post:
    path: '/api/rest/{version}/gridviews.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\DataGridBundle\Controller\Api\Rest\GridViewController::postAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1

oro_datagrid_api_rest_gridview_put:
    path: '/api/rest/{version}/gridviews/{id}.{_format}'
    methods: [PUT]
    defaults:
        _controller: 'Oro\Bundle\DataGridBundle\Controller\Api\Rest\GridViewController::putAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_datagrid_api_rest_gridview_delete:
    path: '/api/rest/{version}/gridviews/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\DataGridBundle\Controller\Api\Rest\GridViewController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_datagrid_api_rest_gridview_default:
    path: '/api/rest/{version}/gridviews/{id}/default/{default}/gridName/{gridName}.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\DataGridBundle\Controller\Api\Rest\GridViewController::defaultAction'
        default: false
        gridName: null
        _format: json
        version: latest
    requirements:
        id: .+
        default: \d+
        grid_name: .+
        _format: json
        version: latest|v1
