services:
    oro_locale.cache:
        parent: oro.data.cache
        tags:
            - { name: 'cache.pool', namespace: 'oro_locale' }

    oro_locale.cache.provider.tree_fallback_strategy:
        parent: oro.data.cache
        tags:
            - { name: 'cache.pool', namespace: 'oro_locale_tree_fallback_strategy' }

    oro_locale.cache.manager:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter
        shared: false
        arguments:
            - '%oro_cache.data_adapter_lifetime%'
            - false

    oro_locale.cache.normalizer.localized_fallback_value:
        class: Oro\Bundle\LocaleBundle\Cache\Normalizer\LocalizedFallbackValueNormalizer
        arguments:
            -
                'id': 'i'
                'string': 's'
                'text': 't'
                'fallback': 'f'
                'localization': 'l'
                'serialized_data': 'd'
            - '@doctrine'

    oro_locale.cache.normalizer.localized_fallback_value_collection:
        class: Oro\Bundle\LocaleBundle\Cache\Normalizer\LocalizedFallbackValueCollectionNormalizer
        arguments:
            - '@oro_locale.cache.normalizer.localized_fallback_value'
