oro_tag_bundle:
    resource:     "@OroTagBundle/Controller/TagController.php"
    type:         attribute
    prefix:       /tag

oro_tag_bundle.taxonomy:
    resource:     "@OroTagBundle/Controller/TaxonomyController.php"
    type:         attribute
    prefix:       /taxonomy


#
# OLD REST API ROUTES
#

oro_api_delete_tag:
    path: '/api/rest/{version}/tags/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\TagBundle\Controller\Api\Rest\TagController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_api_delete_taxonomy:
    path: '/api/rest/{version}/taxonomies/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\TagBundle\Controller\Api\Rest\TaxonomyController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_api_post_taggable:
    path: '/api/rest/{version}/tags/{entity}/{entityId}.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\TagBundle\Controller\Api\Rest\TaggableController::postAction'
        _format: json
        version: latest
    requirements:
        entityId: \d+
        _format: json
        version: latest|v1
