oro_action_widget:
    resource:     "@OroActionBundle/Controller/WidgetController.php"
    type:         attribute
    prefix:       /actionwidget

oro_action_ajax:
    resource:     "@OroActionBundle/Controller/AjaxController.php"
    type:         attribute
    prefix:       /ajax
