security:
    providers:
        chain_provider:
            chain:
                providers:                  [in_memory, oro_user]
        oro_user:
            id:                             oro_user.security.provider
        in_memory:
            memory:
                users:                      []

    password_hashers:
        Oro\Bundle\UserBundle\Entity\User:
            algorithm: sodium
            migrate_from:
                - sha512

    firewalls:
        login:
            pattern:                        ^/user/(login|reset-request|send-email|check-email)$
            provider:                       chain_provider
            context:                        main

        reset_password:
            pattern:                        ^/user/reset/*
            provider:                       chain_provider

        main:
            pattern:                        ^/
            provider:                       chain_provider
            entry_point:                    organization_form_login
            organization-form-login:
                enable_csrf: true
                check_path:                 oro_user_security_check
                login_path:                 oro_user_security_login
                default_target_path:        oro_default
                success_handler:            oro_security.authentication.success_handler
                failure_handler:            oro_security.authentication.failure_handler
            logout:
                path:                       oro_user_security_logout
            organization-remember-me:
                token_provider:             oro_security.token.provider.rememberme
                secret:                     '%kernel.secret%'
                # More info about remember me cookie configuration can be found at
                # https://doc.oroinc.com/backend/setup/post-install/cookies-configuration/#back-office-remember-me-cookie
                name:                       BAPRM
                lifetime:                   1209600   # stay logged for two weeks
                httponly:                   true
            custom_authenticator: oro_user.impersonation_authenticator

oro_security:
    access_control:
        - { path: ^/user/(login|reset-request|send-email|check-email)$, roles: PUBLIC_ACCESS }
        - { path: ^/user/reset/*, roles: PUBLIC_ACCESS }

oro_user:
    privileges:
        entity:
            label: 'oro.user.privileges.entity.label'
            view_type: 'grid'
            types:
                - 'entity'
            field_type: 'oro_acl_access_level_selector'
            fix_values: false
            default_value: 5
            show_default: true
        action:
            label: 'oro.user.privileges.action.label'
            view_type: 'list'
            types:
                - 'action'
            field_type: 'oro_acl_access_level_selector'
            fix_values: false
            default_value: 1
            show_default: false
    login_sources:
        default:
            label: oro.user.login_source.default
            code: 1
        impersonation:
            label: oro.user.login_source.impersonation
            code: 10

oro_entity:
    entity_name_representation:
        Oro\Bundle\UserBundle\Entity\User:
            short: [ firstName, lastName ]
        Oro\Bundle\UserBundle\Entity\Role:
            full: [ label ]
            short: [ label ]

oro_query_designer:
    collapsed_associations:
        Oro\Bundle\UserBundle\Entity\User:
            virtual_fields: [ id ]
            search_fields: [ firstName, lastName ]
