oro_dataaudit_bundle:
    resource:     "@OroDataAuditBundle/Controller"
    type:         attribute
    prefix:       /audit


#
# OLD REST API ROUTES
#

oro_api_get_audits:
    path: '/api/rest/{version}/audits.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\DataAuditBundle\Controller\Api\Rest\AuditController::cgetAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1

oro_api_get_audit:
    path: '/api/rest/{version}/audits/{id}.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\DataAuditBundle\Controller\Api\Rest\AuditController::getAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1

oro_api_get_audit_fields:
    path: '/api/rest/{version}/audit/fields.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\DataAuditBundle\Controller\Api\Rest\AuditController::getFieldsAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1

oro_api_options_audits:
    path: '/api/rest/{version}/audits.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\DataAuditBundle\Controller\Api\Rest\AuditController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1
